<a href="https://colab.research.google.com/github/veetmoradiya3628/Data-engineering-learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

nums = [1, 2, 3, 4, 5]
array1 = np.array(nums)
print(array1)

[1 2 3 4 5]


In [5]:
zero_array = np.zeros(5)
print(zero_array)

[0. 0. 0. 0. 0.]


In [6]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
range_array = np.arange(1, 10, 2)
print(range_array)

[1 3 5 7 9]


In [10]:
random_array = np.random.randint(1, 100, 5)
print(random_array)

[23 51 35 40 11]


In [11]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.08747093 0.11798631 0.90829338]
 [0.86891957 0.94638254 0.23109226]
 [0.28431022 0.01051654 0.32482469]]


In [12]:
shape = range_array.shape
print(shape)

(5,)


In [13]:
size = range_array.size
print(size)

5


In [15]:
dtype = range_array.dtype
print(dtype)

int64


In [16]:
print(range_array.ndim)

1


In [17]:
print(random_matrix.ndim)

2


In [18]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [19]:
print(np.max(array1))
print(np.min(array1))
print(np.max(array2))
print(np.min(array2))

5
1
10
6


In [20]:
greater_than = array1 > 3
print(greater_than)

[False False False  True  True]


In [21]:
result = array1 + 10
print(result)

[11 12 13 14 15]


In [24]:
arr1 = np.array([10, 20, 30, 40, 50])

print(arr1[1])

print(arr1[-2])

20
40


In [25]:
slice_arr = arr1[1:4]
print(slice_arr)

[20 30 40]


In [26]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

mul = np.dot(arr1, arr2)
print(mul)

[[19 22]
 [43 50]]


In [28]:
invr = np.linalg.inv(arr1)
print(invr)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [29]:
eval, evect = np.linalg.eig(arr1)
print(eval)
print(evect)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [30]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
print(mean)
print(std_dev)

3.0
1.4142135623730951


In [32]:
np.savetxt('data.csv', data, delimiter=',')

In [34]:
np.save('data.npy', data) # binary data format, faster format for IO with numpy